import { IncidentRepository } from '../repositories/incident.repository';
import { EventRepository } from '../repositories/event.repository';
import { IIncident } from '../models/Incident.model';
import { ApiError } from '../utils/ApiError';
import { logger } from '../config/logger';

export class IncidentService {
  private incidentRepository: IncidentRepository;
  private eventRepository: EventRepository;

  constructor() {
    this.incidentRepository = new IncidentRepository();
    this.eventRepository = new EventRepository();
  }

  async getAllIncidents(): Promise<IIncident[]> {
    return this.incidentRepository.findAll();
  }

  async getIncidentById(id: string): Promise<IIncident> {
    const incident = await this.incidentRepository.findById(id);
    if (!incident) {
      throw new ApiError(404, `Incident with ID ${id} not found`);
    }
    return incident;
  }

  async getIncidentsByEvent(eventId: string): Promise<IIncident[]> {
    const event = await this.eventRepository.findById(eventId);
    if (!event) {
      throw new ApiError(404, `Event with ID ${eventId} not found`);
    }
    return this.incidentRepository.findByEvent(eventId);
  }

  async createIncident(data: any): Promise<IIncident> {
    if (data.eventId) {
      const event = await this.eventRepository.findById(data.eventId);
      if (!event) {
        throw new ApiError(404, `Event with ID ${data.eventId} not found`);
      }
      if (!data.venueId) {
        data.venueId = event.venueId;
      }
    }

    // Auto-generate sequential ticket ID if not provided
    if (!data.incidentId) {
      const count = await this.incidentRepository.count();
      data.incidentId = `INC-${100 + count + 1}`;
    }

    const savedIncident = await this.incidentRepository.create(data);

    // Trigger Emergency Dispatch protocols cascade
    try {
      const EmergencyServiceClass = (await import('./emergency.service')).default;
      const emergencyService = new EmergencyServiceClass();
      await emergencyService.triggerEmergencyProtocols(savedIncident);
    } catch (err) {
      logger.error(`Failed to trigger emergency cascade: ${err}`);
    }

    return savedIncident;
  }

  /**
   * Automatically triggered when prediction risk level is 'High'
   */
  async createAutomaticIncident(prediction: any): Promise<IIncident> {
    const count = await this.incidentRepository.count();
    const incidentId = `INC-${100 + count + 1}`;

    const incidentDoc = {
      incidentId,
      title: `Automated Congestion Incident: ${prediction.riskLevel} Risk Anomaly`,
      description: `AI Prediction engine flagged high anomaly congestion (Risk: ${prediction.riskLevel}, Confidence: ${prediction.confidence}%). Required mitigations: ${prediction.recommendations.join(', ')}`,
      location: 'Sector Telemetry Gate Grid',
      severity: 'critical' as const,
      status: 'active' as const,
      priority: (prediction.riskLevel === 'Critical' ? 'critical' : 'high') as 'low' | 'medium' | 'high' | 'critical',
      eventId: prediction.eventId,
      venueId: prediction.venueId,
      comments: ['Automated trigger generated by AI Prediction uplink.'],
    };

    logger.warn(`🚨 High Risk anomaly detected! Automatically launching Incident ticket: ${incidentId}`);
    const savedIncident = await this.incidentRepository.create(incidentDoc);

    // Trigger Emergency Dispatch protocols cascade
    try {
      const EmergencyServiceClass = (await import('./emergency.service')).default;
      const emergencyService = new EmergencyServiceClass();
      await emergencyService.triggerEmergencyProtocols(savedIncident);
    } catch (err) {
      logger.error(`Failed to trigger emergency cascade: ${err}`);
    }

    return savedIncident;
  }

  async updateIncident(id: string, data: any): Promise<IIncident> {
    await this.getIncidentById(id);

    if (data.eventId) {
      const event = await this.eventRepository.findById(data.eventId);
      if (!event) {
        throw new ApiError(404, `Event with ID ${data.eventId} not found`);
      }
    }

    const updated = await this.incidentRepository.update(id, data);
    if (!updated) {
      throw new ApiError(400, `Failed to update Incident with ID ${id}`);
    }
    return updated;
  }

  async deleteIncident(id: string): Promise<IIncident> {
    await this.getIncidentById(id);

    const deleted = await this.incidentRepository.delete(id);
    if (!deleted) {
      throw new ApiError(400, `Failed to delete Incident with ID ${id}`);
    }
    return deleted;
  }
}

export default IncidentService;
